Repository Bitmischief/mythweaver, pull requests merged in 2023-09, with the labels that each got.

#153 Suggestion: Add email to env
  api/example.env
  api/prisma/seed.ts
Labels: size/XS

#155 Catch on promise resolution, rather than creation
  api/controllers/rpgSystems.ts
  api/controllers/sessions.ts
  api/index.ts
  api/lib/transactionalEmail.ts
  api/prisma/seed.ts
  api/services/imageGeneration.ts
  api/worker/index.ts
Labels: size/M

#157 156 switch to a new device causes no campaign to be selected
  ui/src/store/campaign.store.ts
Labels: size/XS

#164 158 add saved conjurations filter
  api/controllers/conjurations.ts
  api/routes/conjurations.ts
  ui/package.json
  ui/src/api/conjurations.ts
  ui/src/components/Campaigns/ViewCampaign.vue
  ui/src/components/Conjuration/ConjurationListItemView.vue
  ui/src/components/Conjuration/ConjurationsListFiltering.vue
  ui/src/components/Conjuration/ListConjurations.vue
  ui/src/components/Core/Forms/Autocomplete.vue
  ui/src/views/ConjuringView.vue
  ui/tailwind.config.js
  ui/yarn.lock
Labels: size/L

#160 Bugfix image generation without DATA_DIR folder
  api/services/imageGeneration.ts
Labels: size/XS

#178 finishing session summaries
  api/controllers/campaigns.ts
  api/controllers/sessions.ts
  api/lib/providers/openai.ts
  api/lib/tracking.ts
  api/lib/utils.ts
  api/package.json
  api/prisma/migrations/20230909223616_add_recap_image_uri_and_suggestions_to_session/migration.sql
  api/prisma/migrations/20230910175126_add_status_and_name_to_sessions/migration.sql
  api/prisma/schema.prisma
  api/routes/sessions.ts
  api/services/imageGeneration.ts
  api/worker/index.ts
  api/worker/jobs/completeSession.ts
  api/worker/jobs/conjure.ts
  api/yarn.lock
  ui/public/images/samples/f0c43400-9981-42a8-8421-763064fa691f (1).txt
  ui/public/images/samples/f0c43400-9981-42a8-8421-763064fa691f.txt
  ui/public/images/session_bg.png
  ui/public/images/session_bg_square.png
  ui/src/App.vue
  ui/src/api/sessions.ts
  ui/src/components/Core/Forms/DatePicker.vue
  ui/src/components/Core/Forms/Select.vue
  ui/src/components/Core/Forms/TimePicker.vue
  ui/src/components/Sessions/ListSessions.vue
  ui/src/components/Sessions/NewSession.vue
  ui/src/components/Sessions/Session.vue
  ui/src/components/Sessions/ViewSession.vue
  ui/src/views/SessionsView.vue
Labels: size/XL

#179 Adding Husky to format and lint on commit
  api/.lintstagedrc
  api/.prettierignore
  ui/.husky/pre-commit
  ui/.lintstagedrc
  ui/.prettierignore
  ui/package.json
  ui/yarn.lock
Labels: size/L

#180 Initial setup of codeceptjs and first proof test.
  test/.gitignore
  test/README.md
  test/codecept.conf.ts
  test/package.json
  test/steps.d.ts
  test/steps_file.ts
  test/tsconfig.json
  test/ui/register_early_access_test.ts
  test/yarn.lock
  ui/src/views/LoginView.vue
Labels: size/XXL
