Repository Bitmischief/mythweaver, pull requests merged in 2024-03, with the labels that each got.

#423 Allow editing conjuration before saving
  api/.yarn/install-state.gz
  api/.yarnrc.yml
  api/package-lock.json
  api/yarn.lock
  ui/.yarn/install-state.gz
  ui/.yarnrc.yml
  ui/src/components/Conjuration/ConjurationListItemView.vue
  ui/src/components/Conjuration/ListConjurations.vue
  ui/src/components/Conjuration/ViewConjuration.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
  ui/src/index.css
  ui/yarn.lock
Labels: size/XXL

#425 fix surprise me button
  ui/src/components/Conjuration/ListConjurers.vue
  ui/src/components/Conjuration/ViewConjurer.vue
  ui/src/components/Sessions/ViewSessionTranscription.vue
  ui/yarn.lock
Labels: size/XXL

#426 Fixing prompt limit from 500 to 1000
  api/routes/images.ts
  api/yarn.lock
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjurationImage.vue
Labels: size/XXL

#427 Updating character creation views and functionality
  api/controllers/campaigns.ts
  api/prisma/migrations/20240307003057_drop_unique_constraint_characters_to_campaign_members/migration.sql
  api/prisma/schema.prisma
  api/routes/campaigns.ts
  ui/src/api/characters.ts
  ui/src/components/Characters/NewCharacter.vue
  ui/src/components/Characters/NewCharacter/NewCharacterBasic.vue
  ui/src/components/Characters/NewCharacter/NewCharacterConfirm.vue
  ui/src/components/Characters/NewCharacter/NewCharacterDetailed.vue
  ui/src/components/Characters/NewCharacter/NewCharacterField.vue
  ui/src/components/Characters/NewCharacter/NewCharacterLooks.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjurationImage.vue
  ui/src/components/Navigation/NavbarContent.vue
  ui/src/router/router.ts
  ui/src/views/CharactersList.vue
  ui/src/views/CharactersView.vue
Labels: size/L

#428 Reconjure with same prompt plus bug fixes
  api/controllers/auth.ts
  api/controllers/campaigns.ts
  api/controllers/conjurations.ts
  api/controllers/generators.ts
  api/controllers/images.ts
  api/prisma/migrations/20240307201330_save_prompt_and_seed/migration.sql
  api/prisma/schema.prisma
  api/routes/campaigns.ts
  api/routes/images.ts
  api/services/imageGeneration.ts
  api/worker/jobs/conjure.ts
  ui/src/App.vue
  ui/src/api/campaigns.ts
  ui/src/api/conjurations.ts
  ui/src/api/images.ts
  ui/src/api/rpgSystems.ts
  ui/src/components/Campaigns/NewCampaign.vue
  ui/src/components/Campaigns/OverviewCampaign.vue
  ui/src/components/Campaigns/ViewCampaign.vue
  ui/src/components/Conjuration/ListConjurers.vue
  ui/src/components/Conjuration/ViewConjuration.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjurationImage.vue
  ui/src/components/Images/CustomizableImage.vue
  ui/src/store/campaign.store.ts
Labels: size/XL

#429 return saves count from api
  api/controllers/conjurations.ts
Labels: size/S

#430 fresh package install with new yarn lock
  api/yarn.lock
Labels: size/XXL

#431 Relationships
  api/controllers/relationships.ts
  api/prisma/migrations/20240306174529_add_conjuration_relationships/migration.sql
  api/prisma/migrations/20240306234542_add_conjuration_relationships/migration.sql
  api/prisma/migrations/20240307041303_fix_conjuration_relationships_table_name_typo/migration.sql
  api/prisma/migrations/20240307164837_add_previous_type_and_next_type/migration.sql
  api/prisma/schema.prisma
  api/routes/index.ts
  api/routes/relationships.ts
Labels: size/L

#442 display number of saves a conjuration has in the gallery
  ui/src/api/conjurations.ts
  ui/src/components/Conjuration/ConjurationListItemView.vue
  ui/src/components/Conjuration/ListConjurations.vue
  ui/src/components/Navigation/NavbarContent.vue
Labels: size/M

#444 pre-populate negative prompt when customizing image without refreshing page
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
Labels: size/XS

#445 Adding a v1 of the relationships feature to the UI
  .github/workflows/ui.yml
  api/controllers/conjurations.ts
  api/controllers/relationships.ts
  api/controllers/sessions.ts
  api/prisma/migrations/20240313235223_add_userid_to_conjurationrelationships/migration.sql
  api/prisma/schema.prisma
  api/routes/conjurations.ts
  api/routes/relationships.ts
  api/routes/sessions.ts
  ui/package.json
  ui/src/App.vue
  ui/src/api/conjurations.ts
  ui/src/api/relationships.ts
  ui/src/api/sessions.ts
  ui/src/components/Conjuration/QuickViewConjuration.vue
  ui/src/components/Conjuration/ViewConjuration.vue
  ui/src/components/Core/Spinner.vue
  ui/src/components/Relationships/Create/CreateConjurationRelationship.vue
  ui/src/components/Relationships/Create/CreateSessionRelationship.vue
  ui/src/components/Relationships/CreateRelationship.vue
  ui/src/components/Relationships/ViewRelationships.vue
  ui/src/components/Sessions/ListSessions.vue
  ui/src/components/Sessions/ViewSession.vue
  ui/src/components/Sessions/ViewSessionRelationships.vue
  ui/src/index.css
  ui/src/lib/enums.ts
  ui/src/lib/util.ts
  ui/src/main.ts
  ui/src/router/router.ts
  ui/yarn.lock
Labels: size/XXL

#448 show which relationships already exist in the create relationship modal
  api/controllers/conjurations.ts
  api/controllers/relationships.ts
  api/controllers/sessions.ts
  api/routes/conjurations.ts
  api/routes/sessions.ts
  ui/src/App.vue
  ui/src/api/conjurations.ts
  ui/src/api/relationships.ts
  ui/src/api/sessions.ts
  ui/src/components/Relationships/Create/CreateConjurationRelationship.vue
  ui/src/components/Relationships/Create/CreateSessionRelationship.vue
  ui/src/components/Relationships/ViewRelationships.vue
Labels: size/L

#462 allow saving conjuration from gallery via bookmark icon
  ui/src/components/Conjuration/ConjurationListItemView.vue
  ui/src/components/Conjuration/ListConjurations.vue
Labels: size/M

#463 allow customizing conjuration images using existing seed
  api/controllers/images.ts
  api/routes/images.ts
  api/services/imageGeneration.ts
  ui/src/App.vue
  ui/src/api/images.ts
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjurationImage.vue
  ui/src/components/Images/CustomizableImage.vue
Labels: size/M

#465 Bug/view conjuration mobile
  api/controllers/conjurations.ts
  ui/src/components/Conjuration/ViewConjuration.vue
  ui/src/components/Navigation/NavBar.vue
Labels: size/M

#466 task/improve mobile experience
  ui/src/App.vue
  ui/src/components/Campaigns/OverviewCampaign.vue
  ui/src/components/Characters/CharacterOverview.vue
  ui/src/components/Conjuration/ConjurationListItemView.vue
  ui/src/components/Conjuration/ListConjurations.vue
  ui/src/components/Conjuration/ListConjurers.vue
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjurationImage.vue
  ui/src/components/Navigation/NavBar.vue
  ui/src/components/Navigation/NavbarContent.vue
  ui/src/components/Relationships/CreateRelationship.vue
  ui/src/components/Relationships/ViewRelationships.vue
  ui/src/components/Sessions/ListSessions.vue
  ui/src/components/Sessions/QuickViewSession.vue
  ui/src/components/Sessions/ViewSession.vue
  ui/src/store/conjurations.store.ts
  ui/src/views/CharactersList.vue
  ui/src/views/CharactersView.vue
Labels: size/XL

#467 refactoring some of the campaign logic to handle deleting all campaigns
  ui/src/components/Campaigns/NewCampaign.vue
  ui/src/components/Campaigns/OverviewCampaign.vue
  ui/src/components/Campaigns/ViewCampaign.vue
  ui/src/components/Sessions/ListSessions.vue
  ui/src/store/campaign.store.ts
  ui/src/views/CharactersList.vue
Labels: size/M

#474 Free Tier & Plan Restrictions
  .k8s/api-deployment.yml
  api/controllers/auth.ts
  api/controllers/billing.ts
  api/controllers/conjurations.ts
  api/controllers/sessions.ts
  api/controllers/users.ts
  api/index.ts
  api/package.json
  api/prisma/migrations/20240313172144_make_free_default_plan/migration.sql
  api/prisma/migrations/20240325220913_add_trial_ends_at_date_to_user_table/migration.sql
  api/prisma/migrations/20240326000220_add_trial_plan/migration.sql
  api/prisma/migrations/20240326000311_set_default_trial_plan/migration.sql
  api/prisma/schema.prisma
  api/routes/billing.ts
  api/services/billing.ts
  api/worker/index.ts
  api/worker/jobs/conjure.ts
  api/worker/jobs/endTrials.ts
  api/yarn.lock
  ui/.husky/pre-commit
  ui/public/images/upgrade-container-illustration.svg
  ui/public/images/upgrade-icon.svg
  ui/src/App.vue
  ui/src/api/billing.ts
  ui/src/api/users.ts
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
  ui/src/components/Core/Billing/UpgradeContainer.vue
  ui/src/components/Core/Forms/Select.vue
  ui/src/components/Core/PlanBadge.vue
  ui/src/components/Navigation/NavBar.vue
  ui/src/components/Navigation/NavBarHeader.vue
  ui/src/components/Navigation/TrialInfo.vue
  ui/src/components/Sessions/ViewSessionTranscription.vue
  ui/src/lib/hooks.ts
  ui/src/store/auth.store.ts
  ui/src/views/PreAuthView.vue
Labels: size/XL

#475 Task/mixpanel integration
  .github/workflows/ui_deployment.yml
  ui/package.json
  ui/src/App.vue
  ui/yarn.lock
Labels: size/M

#477 Free tier can save private conjurations that were already private
  api/controllers/conjurations.ts
Labels: size/XS
