Repository Bitmischief/mythweaver, pull requests merged in 2024-12, with the labels that each got.

#763 adding editing undo/redo buttons
  api/modules/images/images.controller.ts
  api/modules/images/images.routes.ts
  api/modules/images/images.service.ts
  api/providers/stabilityAI.ts
  ui/.prettierignore
  ui/components.d.ts
  ui/src/api/images.ts
  ui/src/components/Conjuration/ViewConjuration/CustomizeConjuration.vue
  ui/src/components/Images/CustomizableImage.vue
  ui/src/components/Images/Editing/BrushControls.vue
  ui/src/components/Images/Editing/ImageEditor.vue
  ui/src/components/Images/ImageActions.vue
  ui/src/components/LightboxImage.vue
  ui/src/modules/images/components/GenerateImage.vue
Labels: size/L

#764 poll for runpod updates in worker, move mw image generation to provider
  api/index.ts
  api/modules/images/completedImage.service.ts
  api/modules/images/images.dependencies.ts
  api/modules/images/images.service.ts
  api/modules/images/mythweaverImage.provider.ts
  api/modules/images/mythweaverImage.worker.ts
  api/services/images/mythweaverImageService.ts
  api/services/websockets.ts
  ui/src/lib/serverEvents.ts
  ui/src/modules/images/components/GenerateImageForm.vue
  ui/src/modules/images/components/ViewImage.vue
  ui/src/modules/images/composables/useGenerateImages.ts
  ui/src/modules/images/composables/useGenerationProgress.ts
  ui/src/modules/images/types/image.ts
Labels: size/XL

#768 attempting to fix MYT-57 by adding longer transcription job timeout
  api/worker/jobs/transcribeSession.ts
  ui/src/lib/hooks.ts
  ui/src/modules/images/components/GenerateImageForm.vue
  ui/src/modules/images/components/ModelSelector.vue
  ui/src/modules/images/composables/useGenerateImages.ts
  ui/src/modules/images/composables/useSavedNegativePrompt.ts
  ui/src/modules/images/types/generateImageForm.ts
Labels: size/M

#769 Austin/myt 57 really long transcription jobs can sometimes just be
  api/modules/images/mythweaverImage.provider.ts
  api/modules/images/mythweaverImage.worker.ts
  api/modules/sessions/sessionTranscript.worker.ts
  api/modules/sessions/sessions.controller.ts
  api/modules/sessions/sessions.dependencies.ts
  api/modules/sessions/sessions.interface.ts
  api/modules/sessions/sessions.routes.ts
  api/modules/sessions/sessions.service.ts
  api/modules/sessions/transcription.service.ts
  api/prisma/migrations/20241211190421_add_assembly_transcript_id_to_session/migration.sql
  api/prisma/schema.prisma
  api/providers/assemblyAI.ts
  api/providers/runPod.ts
  api/services/transcription.ts
  api/worker/index.ts
  api/worker/jobs/transcribeSession.ts
  ui/src/api/sessions.ts
  ui/src/components/Sessions/ViewSession.vue
  ui/src/components/Sessions/ViewSessionAudio.vue
  ui/src/components/Sessions/ViewSessionRecap.vue
  ui/src/components/Sessions/ViewSessionSummary.vue
  ui/src/components/Sessions/ViewSessionTranscription.vue
Labels: size/XXL

#772 refactor emal helpers into provider pattern
  api/lib/authMiddleware.ts
  api/modules/billing/billing.dependencies.ts
  api/modules/billing/billing.service.test.ts
  api/modules/billing/billing.service.ts
  api/modules/campaigns/campaigns.dependencies.ts
  api/modules/campaigns/campaigns.service.ts
  api/modules/sessions/sessions.dependencies.ts
  api/modules/sessions/sessions.service.ts
  api/providers/emailProvider.ts
  api/services/internal/email.ts
Labels: size/L

#773 refactor data storage to provider pattern
  api/modules/images/completedImage.service.ts
  api/modules/images/images.service.ts
  api/providers/stabilityAI.ts
  api/providers/storageProvider.ts
  api/services/dataStorage.ts
Labels: size/L

#774 reactor discord to provider pattern
  api/modules/billing/billing.dependencies.ts
  api/modules/billing/billing.service.test.ts
  api/modules/billing/billing.service.ts
  api/providers/discordProvider.ts
  api/services/discord.ts
Labels: size/M

#775 refactor credits helper to provider pattern
  api/lib/authMiddleware.ts
  api/modules/billing/billing.dependencies.ts
  api/modules/billing/billing.service.test.ts
  api/modules/billing/billing.service.ts
  api/modules/images/completedImage.service.ts
  api/modules/images/images.dependencies.ts
  api/modules/images/images.service.ts
  api/modules/users/users.dependencies.ts
  api/modules/users/users.service.ts
  api/providers/creditsProvider.ts
  api/services/credits.ts
  api/services/promptHelper.ts
Labels: size/L

#776 refactor websocket helper to provider patter
  api/lib/authMiddleware.ts
  api/lib/errors/AppError.ts
  api/lib/planRestrictionHelpers.ts
  api/modules/billing/billing.dependencies.ts
  api/modules/billing/billing.service.test.ts
  api/modules/billing/billing.service.ts
  api/modules/campaigns/campaigns.dependencies.ts
  api/modules/campaigns/files/campaignFiles.service.ts
  api/modules/collections/collections.dependencies.ts
  api/modules/collections/collections.service.ts
  api/modules/images/completedImage.service.ts
  api/modules/images/images.dependencies.ts
  api/modules/images/images.service.ts
  api/modules/images/mythweaverImage.worker.ts
  api/modules/sessions/sessionTranscript.worker.ts
  api/modules/sessions/sessions.dependencies.ts
  api/modules/sessions/sessions.service.ts
  api/modules/sessions/transcription.service.ts
  api/modules/users/users.dependencies.ts
  api/modules/users/users.service.ts
  api/providers/creditsProvider.ts
  api/providers/websocketProvider.ts
  api/worker/jobs/conjure.ts
  api/worker/jobs/indexCampaignContext.ts
Labels: size/L

#779 progress converting textGeneration to llm provider
  api/providers/llmProvider.ts
  api/providers/llms/openAIProvider.ts
  api/services/textGeneration.ts
  api/worker/jobs/conjure.ts
Labels: size/M

#780 refactor generate text to new llm provider
  api/providers/llmProvider.ts
  api/providers/llms/openAIProvider.ts
  api/worker/jobs/conjure.ts
Labels: size/M

#781 fixing gpt consumption error after graphite pointed out a bug
  api/providers/llms/openAIProvider.ts
Labels: size/XS

#782 refactor conjure worker
  api/index.ts
  api/modules/conjurations/conjurations.dependencies.ts
  api/modules/conjurations/generateConjuration.worker.ts
  api/modules/core/workers/worker.interface.ts
  api/modules/core/workers/workers.ts
  api/modules/generators/generators.dependencies.ts
  api/modules/generators/generators.service.ts
  api/providers/llms/openAIProvider.ts
  api/providers/websocketProvider.ts
  api/worker/index.ts
  api/worker/jobs/conjure.ts
Labels: size/XL

#783 fix bug wih generator dependencies not resolving
  api/modules/generators/generators.dependencies.ts
Labels: size/XS

#785 fixing package issues
  api/.eslintignore
  api/.eslintrc.js
  api/jest.config.js
  api/modules/images/images.service.ts
  api/tsconfig-paths-bootstrap.js
  api/tsconfig.json
  api/yarn.lock
Labels: size/XXL

#786 refactor tags worker to provider pattern
  api/modules/conjurations/conjurations.dependencies.ts
  api/modules/conjurations/conjurations.service.ts
  api/modules/conjurations/workers/tags.worker.ts
  api/worker/index.ts
  api/worker/jobs/dailyCampaignContextSync.ts
  api/worker/jobs/indexCampaignContext.ts
  api/worker/jobs/processTags.ts
Labels: size/XL
